
server:
  port: 8051

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: https://www.baidu.com
          predicates:
            - Path=/foo/
          filters:
            - StripPrefix=1
      # 与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例
      discovery:
        locator:
          enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8011/eureka/