eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
server:
  port: 9192
spring:
  application:
    name: service-feign
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG

swagger:
  enable: true